// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: currencies.sql

package db

import (
	"context"
)

const getCurrency = `-- name: GetCurrency :one

SELECT code, name, symbol, is_base, decimals, active
FROM currencies
WHERE code = $1
`

type GetCurrencyRow struct {
	Code     string
	Name     string
	Symbol   string
	IsBase   bool
	Decimals int16
	Active   bool
}

// queries/currencies.sql
// currencies is platform-global (no RLS), runs on the bare pool.
func (q *Queries) GetCurrency(ctx context.Context, code string) (GetCurrencyRow, error) {
	row := q.db.QueryRow(ctx, getCurrency, code)
	var i GetCurrencyRow
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.IsBase,
		&i.Decimals,
		&i.Active,
	)
	return i, err
}

const listActiveCurrencies = `-- name: ListActiveCurrencies :many
SELECT code, name, symbol, is_base, decimals, active
FROM currencies
WHERE active
ORDER BY is_base DESC, code
`

type ListActiveCurrenciesRow struct {
	Code     string
	Name     string
	Symbol   string
	IsBase   bool
	Decimals int16
	Active   bool
}

func (q *Queries) ListActiveCurrencies(ctx context.Context) ([]ListActiveCurrenciesRow, error) {
	rows, err := q.db.Query(ctx, listActiveCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCurrenciesRow
	for rows.Next() {
		var i ListActiveCurrenciesRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.IsBase,
			&i.Decimals,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
