// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fx_snapshots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, base_currency, quote_currency, rate, source, captured_at, created_by
FROM fx_snapshots
WHERE base_currency = $1 AND quote_currency = $2
ORDER BY captured_at DESC
LIMIT 1
`

type GetLatestSnapshotParams struct {
	BaseCurrency  string
	QuoteCurrency string
}

func (q *Queries) GetLatestSnapshot(ctx context.Context, arg GetLatestSnapshotParams) (FxSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshot, arg.BaseCurrency, arg.QuoteCurrency)
	var i FxSnapshot
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.Rate,
		&i.Source,
		&i.CapturedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertSnapshot = `-- name: InsertSnapshot :one

INSERT INTO fx_snapshots (base_currency, quote_currency, rate, source, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, base_currency, quote_currency, rate, source, captured_at, created_by
`

type InsertSnapshotParams struct {
	BaseCurrency  string
	QuoteCurrency string
	Rate          decimal.Decimal
	Source        string
	CreatedBy     pgtype.UUID
}

// queries/fx_snapshots.sql
// fx_snapshots is platform-global (no RLS), append only. Runs on the bare pool.
func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) (FxSnapshot, error) {
	row := q.db.QueryRow(ctx, insertSnapshot,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.Rate,
		arg.Source,
		arg.CreatedBy,
	)
	var i FxSnapshot
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.Rate,
		&i.Source,
		&i.CapturedAt,
		&i.CreatedBy,
	)
	return i, err
}

const seedSnapshot = `-- name: SeedSnapshot :exec
INSERT INTO fx_snapshots (base_currency, quote_currency, rate, source)
SELECT $1, $2, $3, 'seed'
WHERE NOT EXISTS (
    SELECT 1 FROM fx_snapshots
    WHERE base_currency = $1 AND quote_currency = $2 AND source = 'seed'
)
`

type SeedSnapshotParams struct {
	BaseCurrency  string
	QuoteCurrency string
	Rate          decimal.Decimal
}

func (q *Queries) SeedSnapshot(ctx context.Context, arg SeedSnapshotParams) error {
	_, err := q.db.Exec(ctx, seedSnapshot, arg.BaseCurrency, arg.QuoteCurrency, arg.Rate)
	return err
}
