// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type AuditLog struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	ActorID    pgtype.UUID
	Action     string
	TargetType string
	TargetID   pgtype.UUID
	Detail     string
	RequestID  string
	OccurredAt pgtype.Timestamptz
}

type Currency struct {
	Code      string
	Name      string
	Symbol    string
	IsBase    bool
	Decimals  int16
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type FxSnapshot struct {
	ID            pgtype.UUID
	BaseCurrency  string
	QuoteCurrency string
	Rate          decimal.Decimal
	Source        string
	CapturedAt    pgtype.Timestamptz
	CreatedBy     pgtype.UUID
}

type TenantFxConfig struct {
	TenantID        pgtype.UUID
	DisplayCurrency string
	FxSource        string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
