// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// queries/currencies.sql
	// currencies is platform-global (no RLS), runs on the bare pool.
	GetCurrency(ctx context.Context, code string) (GetCurrencyRow, error)
	GetLatestSnapshot(ctx context.Context, arg GetLatestSnapshotParams) (FxSnapshot, error)
	// queries/tenant_config.sql
	// tenant_fx_config is tenant scoped (RLS via WithTenant).
	GetTenantConfig(ctx context.Context, tenantID pgtype.UUID) (GetTenantConfigRow, error)
	// queries/audit.sql
	// audit_log is tenant scoped (RLS via WithTenant).
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// queries/fx_snapshots.sql
	// fx_snapshots is platform-global (no RLS), append only. Runs on the bare pool.
	InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) (FxSnapshot, error)
	ListActiveCurrencies(ctx context.Context) ([]ListActiveCurrenciesRow, error)
	QueryAuditLog(ctx context.Context, arg QueryAuditLogParams) ([]AuditLog, error)
	SeedSnapshot(ctx context.Context, arg SeedSnapshotParams) error
	UpsertTenantConfig(ctx context.Context, arg UpsertTenantConfigParams) (UpsertTenantConfigRow, error)
}

var _ Querier = (*Queries)(nil)
