// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantConfig = `-- name: GetTenantConfig :one

SELECT tenant_id, display_currency, fx_source, updated_at
FROM tenant_fx_config
WHERE tenant_id = $1
`

type GetTenantConfigRow struct {
	TenantID        pgtype.UUID
	DisplayCurrency string
	FxSource        string
	UpdatedAt       pgtype.Timestamptz
}

// queries/tenant_config.sql
// tenant_fx_config is tenant scoped (RLS via WithTenant).
func (q *Queries) GetTenantConfig(ctx context.Context, tenantID pgtype.UUID) (GetTenantConfigRow, error) {
	row := q.db.QueryRow(ctx, getTenantConfig, tenantID)
	var i GetTenantConfigRow
	err := row.Scan(
		&i.TenantID,
		&i.DisplayCurrency,
		&i.FxSource,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantConfig = `-- name: UpsertTenantConfig :one
INSERT INTO tenant_fx_config (tenant_id, display_currency, fx_source)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id) DO UPDATE
SET display_currency = EXCLUDED.display_currency,
    fx_source        = EXCLUDED.fx_source,
    updated_at       = now()
RETURNING tenant_id, display_currency, fx_source, updated_at
`

type UpsertTenantConfigParams struct {
	TenantID        pgtype.UUID
	DisplayCurrency string
	FxSource        string
}

type UpsertTenantConfigRow struct {
	TenantID        pgtype.UUID
	DisplayCurrency string
	FxSource        string
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertTenantConfig(ctx context.Context, arg UpsertTenantConfigParams) (UpsertTenantConfigRow, error) {
	row := q.db.QueryRow(ctx, upsertTenantConfig, arg.TenantID, arg.DisplayCurrency, arg.FxSource)
	var i UpsertTenantConfigRow
	err := row.Scan(
		&i.TenantID,
		&i.DisplayCurrency,
		&i.FxSource,
		&i.UpdatedAt,
	)
	return i, err
}
